# Generated by Django 3.0.8 on 2021-12-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloNoticia', models.CharField(max_length=200)),
                ('corpoNoticia', models.TextField()),
                ('dataNoticia', models.DateField()),
            ],
        ),
    ]
